name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      # Install PM2
      - name: Install PM2
        run: npm install pm2 -g

      # Stop all instances of PM2
      - name: Stop all instances of PM2
        run: sudo pm2 delete all || true

      # Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Create environment variables for each service
      - name: Create environment variables
        run: |
          touch .env
          echo "${{ secrets.PROD_ENV }}" > .env

      # Start Node.js applications using PM2
      - name: Start Node.js application
        run: sudo pm2 start server.js --name="server" -f
