name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      # Install PM2 globally using full path to npm
      - name: Install PM2
        run: sudo /usr/local/bin/npm install pm2 -g

      # Stop all instances of PM2 (run as root)
      - name: Stop all instances of PM2
        run: sudo /usr/local/bin/pm2 delete all || true

      # Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Create environment variables file
      - name: Create environment variables
        run: echo "${{ secrets.PROD_ENV }}" > .env

      # Start Node.js application using PM2 (run as root)
      - name: Start Node.js application
        run: sudo /usr/local/bin/pm2 start server.js --name="server" -f
